#!/usr/bin/env python3
"""§6.6 BoundMeet property test (Python side, rev CLC-1.15).

Runs the deterministic case list shared with the Go and TypeScript
implementations (`capability/data/_vectors/clc-v1/param-bounds-meet-property-cases.json`,
generated by `capability/scripts/gen-param-bounds-meet-property-cases.py`).
For every case of sources S:

  1. **Fail-closed.**  intersect(S) never raises an unexpected error, and a
     refusal always carries a normative reason code (§9.2).
  2. **The meet invariant.**  When intersect(S) succeeds with grant G, then
     for every operation o in the shared sample:
         Entails(G, o)  ==>  Entails(s, o) for EVERY source s in S.
     Every successful meet authorizes only operations that each source
     authorizes on its own — the law the CLC-1.14 filtered-enum reduction
     violated (the enum{3} meet accepted the array [3] while the numeric
     source fail-closed it).
  3. **Order independence on success.**  When the forward merge succeeds, the
     reversed merge succeeds too and yields the identical canonical result
     (§7 rules 2/6).  A refused merge may refuse with a different code under
     a different fold order; only the refusal itself must be stable.

Usage:
    python3 param-bounds-meet-property-run.py
    CLC_PARAM_BOUNDS_MEET_PROPERTY_CASES=/path/to/cases.json python3 param-bounds-meet-property-run.py
"""
import json
import os
import sys

from clc_semantics import CLCError, canonical_reason, entails, intersect

NORMATIVE_CODES = {
    "unsupported_language_revision", "invalid_capability_id", "missing_capability_id",
    "unsupported_wildcard", "invalid_params_duplicate_key", "invalid_params_number",
    "invalid_params_size", "invalid_params_binding", "params_cardinality",
    "params_out_of_range", "params_not_multiple", "different_namespace",
    "literal_mismatch", "wildcard_requires_trailing_segment",
    "empty_bound_denies_class", "invalid_params_null", "params_missing",
    "undeclared_param", "not_in_enum", "params_exceed_grant", "no_overlap",
    "absent_source", "capability_not_authorized", "unknown_constraint",
}


def canonical_grant(g):
    keys = ("id", "params", "param_bounds", "constraints")
    return json.dumps({k: g.get(k) for k in keys}, sort_keys=True)


def main():
    path = os.environ.get("CLC_PARAM_BOUNDS_MEET_PROPERTY_CASES")
    if not path:
        path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "..", "capability", "data", "_vectors", "clc-v1",
                            "param-bounds-meet-property-cases.json")
    if not os.path.exists(path):
        print("meet property cases not found at %s (set CLC_PARAM_BOUNDS_MEET_PROPERTY_CASES)" % path)
        return 0

    with open(path) as f:
        doc = json.load(f)
    cases, ops = doc["cases"], doc["ops"]

    meets = 0
    order_checked = 0
    op_checks = 0
    failures = []

    for case in cases:
        sources = [dict(s) for s in case["sources"]]
        try:
            merged = intersect([dict(s) for s in sources])
        except CLCError as e:
            code = canonical_reason(str(e))
            if code not in NORMATIVE_CODES:
                failures.append("%s: denial %r is not a normative reason code" % (case["id"], code))
            continue

        meets += 1

        # The meet invariant: G authorizes o only when EVERY source authorizes o.
        for o in ops:
            op_checks += 1
            if not entails(merged, o)["entails"]:
                continue
            for i, s in enumerate(sources):
                if not entails(s, o)["entails"]:
                    failures.append(
                        "%s: meet authorizes op but source %d does not — op=%s merged=%s source=%s"
                        % (case["id"], i, json.dumps(o, sort_keys=True),
                           canonical_grant(merged), json.dumps(s, sort_keys=True)))
                    break

        # Order independence on success.
        try:
            other = intersect([dict(s) for s in reversed(sources)])
        except CLCError as e:
            failures.append("%s: reversed order denies (%s) while the original allows" % (case["id"], e))
        else:
            if canonical_grant(other) != canonical_grant(merged):
                failures.append("%s: result depends on source order: %s vs %s"
                                % (case["id"], canonical_grant(merged), canonical_grant(other)))
        order_checked += 1

    for f_ in failures[:20]:
        print("FAIL " + f_)
    print("meet-property: %d cases, %d successful meets, %d order-symmetry checks, "
          "%d op-checks, %d failures"
          % (len(cases), meets, order_checked, op_checks, len(failures)))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
