#!/usr/bin/env python3
"""P11 property test (Python side) — "composition narrows only" (CLC-v1 §7).

Runs the deterministic case list shared with the Go implementation
(`capability/data/_vectors/clc-v1/property-cases.json`, generated by
`capability/scripts/gen-property-cases.py`).  For every case of sources S:

  1. **Source coverage (⊑, §7 rule 2).**  For every source and every parameter
     key that source declares, the merged bound is within the source's bound;
     the source's identifier covers the merged identifier; no constraint of any
     source is dropped.  Keys a source does not declare are ignored here —
     composition authorizes a key when *some* source declares it.
  2. **Order independence.**  Merging the sources in reverse yields the same id,
     params and constraints (or denies as well).
  3. **Closure belongs to the effective grant (§9.3 layer 7).**  When the merged
     grant is bounded, an operation carrying a parameter key that no source
     declared is denied with `undeclared_param`; when the merged grant has no
     params at all it is unconstrained and the extra key is permitted.
  4. **Fail-closed.**  A denial always carries a normative reason code (§9.4),
     never an exception.

Both implementations run this file; verified parity here plus on the corpus is
the v1 conformance bar (principles P11/P12).

Usage:
    python3 property_test.py
    CLC_PROPERTY_CASES=/path/to/property-cases.json python3 property_test.py
"""
import json
import os
import sys

from clc_semantics import (CLCError, authorize, entails, params_subset,
                           canonical_reason)

NORMATIVE_CODES = {
    "unsupported_language_revision", "invalid_capability_id", "missing_capability_id",
    "unsupported_wildcard", "invalid_params_duplicate_key", "invalid_params_number",
    "invalid_params_size", "different_namespace", "literal_mismatch",
    "wildcard_requires_trailing_segment", "empty_bound_denies_class",
    "invalid_params_null", "params_missing", "undeclared_param", "not_in_enum",
    "params_exceed_grant", "no_overlap", "absent_source",
    "capability_not_authorized", "unknown_constraint",
}


def covered_by_source(merged, src):
    """⊑: the merged grant stays inside the source on the source's own keys."""
    # Identifier coverage, deliberately params-free: entails() fails closed when
    # a bounded grant meets an operation with no params (§6.3 step 4).
    if not entails({"id": src["id"]}, {"id": merged["id"]})["entails"]:
        return False
    if src.get("params") is None:
        return True
    for key, bound in src["params"].items():
        if key not in (merged.get("params") or {}):
            return False
        ok, _ = params_subset({key: merged["params"][key]}, {key: bound})
        if not ok:
            return False
    for con in src.get("constraints") or []:
        if con not in (merged.get("constraints") or []):
            return False
    return True


def main():
    path = os.environ.get("CLC_PROPERTY_CASES")
    if not path:
        path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "..", "capability", "data", "_vectors", "clc-v1",
                            "property-cases.json")
    if not os.path.exists(path):
        print("property cases not found at %s (set CLC_PROPERTY_CASES)" % path)
        return 0

    with open(path) as f:
        cases = json.load(f)["cases"]

    order_checked = 0
    closure_checked = 0
    failures = []

    for case in cases:
        sources = case["sources"]
        if not sources:
            continue

        try:
            from clc_semantics import intersect
            merged = intersect([dict(s) for s in sources])
        except CLCError as e:
            code = canonical_reason(str(e))
            if code not in NORMATIVE_CODES:
                failures.append("%s: denial %r is not a normative reason code" % (case["id"], code))
            continue

        for i, src in enumerate(sources):
            if not covered_by_source(merged, src):
                failures.append("%s (%s): result %s is NOT covered by source %d %s"
                                % (case["id"], case.get("note", ""), json.dumps(merged, sort_keys=True),
                                   i, json.dumps(src, sort_keys=True)))

        # Closure applies to the effective grant only.
        if merged.get("id") and merged.get("params") is not None:
            probe = {"id": merged["id"],
                     "params": dict(merged["params"], clc_undeclared_probe="x")}
            decision = authorize(merged, probe)
            if canonical_reason(decision.get("reason", "")) != "undeclared_param":
                failures.append("%s: operation with an undeclared key resolved to %r, want undeclared_param"
                                % (case["id"], decision.get("reason")))
            closure_checked += 1

        if len(sources) > 1:
            try:
                from clc_semantics import intersect
                other = intersect([dict(s) for s in reversed(sources)])
            except CLCError as e:
                failures.append("%s: reversed order denies (%s) while the original allows" % (case["id"], e))
            else:
                keys = ("id", "params", "constraints")
                a = json.dumps({k: merged.get(k) for k in keys}, sort_keys=True)
                b = json.dumps({k: other.get(k) for k in keys}, sort_keys=True)
                if a != b:
                    failures.append("%s: result depends on source order: %s vs %s" % (case["id"], a, b))
            order_checked += 1

    for f_ in failures[:20]:
        print("FAIL " + f_)
    print("property: %d cases, %d order-symmetry checks, %d closure probes, %d failures"
          % (len(cases), order_checked, closure_checked, len(failures)))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
